### ISSUE TITLE
Compiling final assets

### ISSUE THREAD

**Issue by androide-osorio** [nosoycesaros/react-quickstart#2]
Currently, there is no way to export the code built with the quickstart to valid HTML, CSS or JavaScript that is ready to be served in production or any other environment. (in an easy, straightforward way)

I suggest we build a simple dev and production pipeline with Webpack. As of right now, we already have a decent dev environment. We just need a production setup that:

* converts ES2015 and JSX code to ES5.
* de-duplicates any reused code.
* Separates style files from their `import` statements in JS, into their own separate file.
* Uglifies/minifies the code.
* Export the bundled CSS,  JS and HTML files that are ready to be used by any browser.
* exports source maps for development and debugging purposes.

I think it is a good idea (and following what we have so far) to create an `npm` script that does this. Hence, we can just run something like:
```bash
$ npm run build
```
and boom!!! 💣 : we have production files.

Let me know what you think 😃

**Comment by nosoycesaros** [comment]
@androide-osorio just added this feature in our last version: Compiling project #4
